title: Awesome Life   
description: > # this means to ignore newlines until "baseurl:"
  윈도우즈 및 리눅스 터미널 환경에서 할 수 있는 것들에 대한 정보를 공유하기 위한 블로그입니다. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://butteryoon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: softroom #if your site has a twitter account, enter it here
#permalink: ':title/'

# Author Settings
author: James Yoon # add your name
author-img: me_profile.jpg # add your photo
about-author: Development and Management of Developer's Perspective # add description
social-twitter: softroom # add your Twitter handle
social-facebook: softroom75 # add your Facebook handle
social-github: butteryoon # add your Github handle
social-linkedin: softroom # add your Linkedin handle
social-email: softroom@naver.com # add your Email address

# Disqus
disqus-identifier: awesome-life # add your disqus identifier

# Tracker
analytics: UA-126917874-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-youtube

paginate: 10
paginate_path: "/page/:num"

excerpt_separator: <!--more-->

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

include:
  - _static

# text highlighter로 rouge이용
highlighter: rouge

# Navigation bar link를 보여줄건지 여부
navigation: True

gist:
  noscript: false
